config/routes.rb
Rails.application.routes.draw do

  get '/classes' => 'player_character_classes#index', as:'classes'
  post '/classes' => 'player_character_classes#index'
  get '/class/show' => 'player_character_classes#show', as: 'class'
  post '/class/:id' => 'player_character_classes#show'

  post '/races/:id' => 'races#show', as:'race_lookup'

  get '/equipments/:player_character_id/index' => 'equipments#index', as:'equipments_buy'
  get '/equipments/:player_character_id/sell_index' => 'equipments#sell_index', as: 'equipments_sell'
 
 post '/equipments' => 'equipments#create'
 delete '/equipments' => 'equipments#destroy' 
  get '/achievements/:game_id', to: 'achievements#index', as:'achievements'
  post '/achievements', to:'achievements#create'

  get 'experiencepoints/:game_id', to: 'experiencepoints#index', as: 'experiencepoints'

  patch '/experiencepoints', to: 'experiencepoints#update'
  put '/experiencepoints', to: 'experiencepoints#update'

  get '/player_characters/:id/achievement' => 'player_characters#achievement', as: 'player_character_achievement'

  get '/attack_weapons/:player_character_id/index' => 'attack_weapons#index', as: 'attack_weapons_buy'

  get '/attack_weapons/:player_character_id/sell_index' => 'attack_weapons#sell_index', as: 'attack_weapons_sell'
  post '/attack_weapons' => 'attack_weapons#create'
  delete '/attack_weapons' => 'attack_weapons#destroy' #selling attack_weapon

  get '/armor_and_shields/:player_character_id/index' => 'armor_and_shields#index', as:'armor_and_shields_buy'
  get '/armor_and_shields/:player_character_id/sell_index' => 'armor_and_shields#sell_index', as:'armor_and_shields_sell'
  post '/armor_and_shields' => 'armor_and_shields#create'
  delete '/armor_and_shields' => 'armor_and_shields#destroy' #selling action

  get 'join_game/new'

  get 'join_game/join_game_form'

  

  post '/player_characters/ajaxwindow/:background' => 'player_characters#ajaxwindow' 

  resources :player_characters
  post '/player_characters/ajaxwindow/:background' => 'player_characters#ajaxwindow' 
  get '/player_characters/:id/otheruser' => 'player_characters#showOthers', as: 'otheruser'

  get '/player_characters/:id/market' => 'player_characters#market', as: 'player_character_market'

  get '/player_characters/2/edit' => 'player_characters#edit'

  root 'users#new'
  get 'users', to:'users#index', as: 'users'
  get '/users/new', to: 'users#new', as: 'new_users'

  post '/users', to: 'users#create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/users/:id' => 'users#show', as: 'user'
  
  delete '/users/:id' => 'users#delete'

  get '/games' => 'games#index', as: 'games'
  get '/games/new' => 'games#new', as:'new_game'
  
  get '/games/:id' => 'games#show', as:'game'

  get '/games/:id/edit' => 'games#edit', as:'edit_game'
  patch '/games/:id', to: 'games#update'
  put '/games/:id', to: 'games#update'
  
  delete '/games/:id', to: 'games#leaveGame'

  post '/games' => 'games#create'

  delete '/games' => 'games#destroy'

  get '/game_invitations' => 'game_invitations#index', as:'game_invitations'
  put '/game_invitations' => 'game_invitations#index'
  get '/game_invitations/:game_id/new' => 'game_invitations#new', as:'new_game_invitation'
  post '/game_invitations' => 'game_invitations#create'
  
  delete 'game_invitations' => 'game_invitations#destroy'

  

  get '/join_game/:game_id/new' => 'join_game#new', as:'join_game'
  post '/join_game/:game_id/new' => 'join_game#user_input'
    

  

  delete '/game_invitations' =>'join_game#user_input'

  

end

app/models/game_invitation.rb
# == Schema Information
#
# Table name: game_invitations
#
#  id                :integer          not null, primary key
#  game_password     :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  game_id           :integer
#  dungeon_master_id :integer
#  user_player_id    :integer
#




class GameInvitation < ActiveRecord::Base
	validate :user_cannot_be_both_dungeon_master_and_player_in_the_same_game, :no_valid_user_provided,:no_invalid_users_can_be_specified

	validates:game_password, presence:true

	belongs_to :dungeon_master,
				class_name: "User",
				foreign_key: "dungeon_master_id"

	belongs_to :user_player,
				class_name: "User",
				foreign_key: "user_player_id"

	belongs_to :game,
				class_name: "Game",
				foreign_key: "game_id"

	#non-persistent model attribute to keep track of list of user_names provided in view
	attr_accessor :user_names, :invalid_user_names, :all_users_invalid

	def user_cannot_be_both_dungeon_master_and_player_in_the_same_game
    if user_player != nil and dungeon_master == user_player
      errors.add(:user_player, " #{user_player.user_name} can not be both dungeon_master and player in same game")
    end

    def no_invalid_users_can_be_specified
    	unless invalid_user_names.nil?
    		invalid_users = ''
    		invalid_user_names.each do |invalid_user_name|
    			if invalid_users.length == 0
    				invalid_users = invalid_user_name
    			else
    				invalid_users = "#{invalid_users};#{invalid_user_name}"
    			end
    		end
    		errors.add(:user_player, "(s) contains some invalid users #{invalid_users}")
    	end
    end

    def no_valid_user_provided
    	if user_player.nil? and all_users_invalid
    		errors.add(:user_player, "(s) specified are all invalid")
    	end
    end

  end
end

app/controllers/game_invitations_controller.rb
class GameInvitationsController < ApplicationController
	before_action :logged_in_user, only: [:index,:new,:create]
  	before_action :is_dungeon_master_user,   only: [:new]

	def new
		@game_invitation = GameInvitation.new
		game = Game.find(params[:game_id])
		@game_invitation.game = game
	end

	def index
		@game_invitations_sent = current_user.game_invitations_sent
		@game_invitations_received = current_user.game_invitations_received
	end

	def create
		#@game_invitation = GameInvitation.new(params.require(:game_invitation).permit(:game_password))
		game = Game.find(params[:game_invitation][:game])

		#somebody tampered with hidden game_id
		if game.nil?
			flash[:alert] = "Game Invitation form tampered!"
			return redirect_to user_path(current_user)
		end 


		user_player = params[:game_invitation][:user_player]
		#game_password = params[:game_invitation][:game_password]
		game_password = game.game_password

		user_names = user_player.strip.split(";")
		valid_gameinvitations = []
		valid_users = []
		invalid_user_names = []
		provided_user_count = 0
		user_names.each do |user_name|
			user_name = user_name.strip
			if user_name.length > 0
				provided_user_count = provided_user_count + 1
				user = User.find_by user_name: user_name
				if user != nil
					#if game.dungeon_master == user
						#flash[:alert] = "a user can not be both dungeon_master and player in same game"
						#return redirect_to new_game_invitation_path(game)
					#end
					#may want to keep track of valid users
					valid_users.push(user_name)
					@game_invitation = GameInvitation.new
					@game_invitation.game = game
					@game_invitation.game_password = game_password
					@game_invitation.user_player = user
					@game_invitation.dungeon_master = game.dungeon_master
					@game_invitation.user_names = user_names
					if @game_invitation.valid?
						valid_gameinvitations.push(@game_invitation) 
					else
						render 'new' #unless @game_invitation.save
						return
					end
				else
					invalid_user_names.push(user_name)
				end
			end
		end

		if valid_users.length == 0
			#flash[:alert] =  "no valid users provided!"
			@game_invitation = GameInvitation.new
			@game_invitation.game = game
			@game_invitation.game_password = game_password
			@game_invitation.dungeon_master = game.dungeon_master
			@game_invitation.user_names = user_names
			@game_invitation.all_users_invalid = true
			render 'new' unless @game_invitation.valid?
			return
		end

		#check number of valid users = number os users specified
		if valid_users.length == provided_user_count
			#now save each of valid game-invitations
			valid_gameinvitations.each do |game_invitation|
				@game_invitation = game_invitation
				unless @game_invitation.save
					render 'new' 
					return
				end
			end
		else
			@game_invitation = GameInvitation.new
			@game_invitation.game = game
			@game_invitation.game_password = game_password
			@game_invitation.all_users_invalid = false
			@game_invitation.invalid_user_names =invalid_user_names
			@game_invitation.user_names = user_names
			render 'new' unless @game_invitation.valid?
			return
		end

		
		users = valid_users.join(',')
		flash[:success] = users + " successfully invited to the game!"
		redirect_to game_path(game)
	end

    
   def destroy
		@invitation_id = params[:game_inv_id];
        GameInvitation.destroy(params[:game_inv_id]);
        redirect_to game_invitations_path
	end



	private
    # Confirms if the user is dungeon user.
	 def is_dungeon_master_user
	    game = Game.find_by id: params[:game_id]
	    if game.nil? or !dungeon_master?(game.dungeon_master)
	    	redirect_to(root_url) 
	    end 
	 end

	
end

app/helpers/game_invitations_helper.rb
module GameInvitationsHelper
end

app/views/game_invitations/index.html.erb
<% provide(:title, 'GameInvitations-Index') %>

<div style="margin-top: 10px;">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Pending Game Invitations Sent</div>

    <!-- Table -->
    <table class="table">
      <tr>
        <th>Game Name</th>
        <th>Invited Users</th>
        <th> &nbsp;&nbsp;</th>
      </tr>
      <% @game_invitations_sent.each do |game_invitation| %>
      <tr>
        <% if(game_invitation.game!=nil && game_invitation.user_player!=nil) %>
            <td><%= game_invitation.game.name %></td>
            <td><%= game_invitation.user_player.user_name %></td>
            <td><%= link_to "Cancel", game_invitations_path(game_inv_id: game_invitation.id), data: { confirm: 'Are you sure?' }, method: :delete %></td>

        <% end %>    
      </tr>
      <% end %>
  </table>
  </div>
</div>


<div style="margin-top: 10px;">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Pending Game Invitations Received</div>

    <!-- Table -->
    <table class="table">
      <tr>
        <th>Game Name</th>
        <th>Dungeon Master</th>
        <th>Game Password</th>
        <th colspan=2 > &nbsp;&nbsp;</th>
      </tr>
      <% @game_invitations_received.each do |game_invitation| %>
      <tr>
        <td><%= game_invitation.game.name %></td>
      <td><%= game_invitation.dungeon_master.user_name %></td>
      <td><%= game_invitation.game_password %></td>
      <td><%= link_to "Accept", join_game_path({game_id: game_invitation.game.id, game_inv_id: game_invitation.id} ) %></td> 
      <td><%= link_to "Reject", game_invitations_path(game_inv_id: game_invitation.id), data: { confirm: 'Are you sure?' }, method: :delete %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>



  <div class="col-sm-12">
  <hr>
  <%= link_to "Go to User Home page",user_path(current_user) %>
</div>

app/views/game_invitations/new.html.erb
<% provide(:title, "GameInvitation-Add") %>

<% if @game_invitation.errors.any? %>
<div id="error_explanation">
      <h2><%= pluralize(@game_invitation.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game_invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
</div>
<% end %>

<div style="margin-top: 10px;">
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">Invite User(s)</div>
	 </div>
	  <div id="game_invitation_content">
		<%= form_for(@game_invitation) do |f| %>
			<div class='form-group'>
		    	<%= f.label :name,'Game Name:',class: "col-sm-3 control-label"%>
		    	<%= f.label :name,@game_invitation.game.name,class: "col-sm-9 control-label"%>
			</div>
			<%= f.hidden_field :game, :value => @game_invitation.game.id %>
			<%= f.hidden_field :game_password, :value => @game_invitation.game.game_password %>
			<div class='form-group'>
				<div class="col-sm-3">
		    		<%= f.label :user_player,'Invite Users ( use ; to add multiple users ) :'%>
		    	</div>
		    	<div class="col-sm-9">
		    		<% user_player_name = ""
		    		unless @game_invitation.user_names.nil?
		    			@game_invitation.user_names.each do |user_name|
		    				if user_player_name.length == 0
		    					user_player_name = user_name
		    				else
		    					user_player_name = "#{user_player_name};#{user_name}"
		    				end
		    			end
		    		end
		    		%>
		    		<%= f.text_field :user_player, :value =>user_player_name,  class: 'form-control'%>
				</div>
			</div>
			<div class="form-group">
	    		<div class="col-sm-offset-3 col-sm-9">
					<%= f.submit "Invite User(s)" %>&nbsp;<%= button_tag "Reset", type: :reset %>
				</div>
			</div>
		<% end %>
		</div>	
	</div>


<div class="col-sm-12">
	<hr>
	<%= link_to "Go to Game page",game_path(@game_invitation.game) %>
</div>