config/routes.rb
Rails.application.routes.draw do

  get '/classes' => 'player_character_classes#index', as:'classes'
  post '/classes' => 'player_character_classes#index'
  get '/class/show' => 'player_character_classes#show', as: 'class'
  post '/class/:id' => 'player_character_classes#show'

  post '/races/:id' => 'races#show', as:'race_lookup'

  get '/equipments/:player_character_id/index' => 'equipments#index', as:'equipments_buy'
  get '/equipments/:player_character_id/sell_index' => 'equipments#sell_index', as: 'equipments_sell'
 
 post '/equipments' => 'equipments#create'
 delete '/equipments' => 'equipments#destroy' 
  get '/achievements/:game_id', to: 'achievements#index', as:'achievements'
  post '/achievements', to:'achievements#create'

  get 'experiencepoints/:game_id', to: 'experiencepoints#index', as: 'experiencepoints'

  patch '/experiencepoints', to: 'experiencepoints#update'
  put '/experiencepoints', to: 'experiencepoints#update'

  get '/player_characters/:id/achievement' => 'player_characters#achievement', as: 'player_character_achievement'

  get '/attack_weapons/:player_character_id/index' => 'attack_weapons#index', as: 'attack_weapons_buy'

  get '/attack_weapons/:player_character_id/sell_index' => 'attack_weapons#sell_index', as: 'attack_weapons_sell'
  post '/attack_weapons' => 'attack_weapons#create'
  delete '/attack_weapons' => 'attack_weapons#destroy' #selling attack_weapon

  get '/armor_and_shields/:player_character_id/index' => 'armor_and_shields#index', as:'armor_and_shields_buy'
  get '/armor_and_shields/:player_character_id/sell_index' => 'armor_and_shields#sell_index', as:'armor_and_shields_sell'
  post '/armor_and_shields' => 'armor_and_shields#create'
  delete '/armor_and_shields' => 'armor_and_shields#destroy' #selling action

  get 'join_game/new'

  get 'join_game/join_game_form'

  

  post '/player_characters/ajaxwindow/:background' => 'player_characters#ajaxwindow' 

  resources :player_characters
  post '/player_characters/ajaxwindow/:background' => 'player_characters#ajaxwindow' 
  get '/player_characters/:id/otheruser' => 'player_characters#showOthers', as: 'otheruser'

  get '/player_characters/:id/market' => 'player_characters#market', as: 'player_character_market'

  get '/player_characters/2/edit' => 'player_characters#edit'

  root 'users#new'
  get 'users', to:'users#index', as: 'users'
  get '/users/new', to: 'users#new', as: 'new_users'

  post '/users', to: 'users#create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/users/:id' => 'users#show', as: 'user'
  
  delete '/users/:id' => 'users#delete'

  get '/games' => 'games#index', as: 'games'
  get '/games/new' => 'games#new', as:'new_game'
  
  get '/games/:id' => 'games#show', as:'game'

  get '/games/:id/edit' => 'games#edit', as:'edit_game'
  patch '/games/:id', to: 'games#update'
  put '/games/:id', to: 'games#update'
  
  delete '/games/:id', to: 'games#leaveGame'

  post '/games' => 'games#create'

  delete '/games' => 'games#destroy'

  get '/game_invitations' => 'game_invitations#index', as:'game_invitations'
  put '/game_invitations' => 'game_invitations#index'
  get '/game_invitations/:game_id/new' => 'game_invitations#new', as:'new_game_invitation'
  post '/game_invitations' => 'game_invitations#create'
  
  delete 'game_invitations' => 'game_invitations#destroy'

  

  get '/join_game/:game_id/new' => 'join_game#new', as:'join_game'
  post '/join_game/:game_id/new' => 'join_game#user_input'
    

  

  delete '/game_invitations' =>'join_game#user_input'

  

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id            :integer          not null, primary key
#  name          :string
#  map           :string
#  game_history  :text
#  game_password :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#





class Game < ActiveRecord::Base
	validates:name, presence:true,uniqueness:true
	validates:game_password,presence:true

	belongs_to :dungeon_master,
				class_name: "User",
				foreign_key: "user_id"

	has_many :game_invitations,
			class_name: "GameInvitation",
			foreign_key: "game_id"


    has_many :player_characters
    has_many :achievements

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :logged_in_user, only: [:show,:index,:update,:edit,:new,:create]
  	before_action :is_dungeon_master_user,   only: [:edit,:update]

	def index
		@user_owned_games = current_user.games_created
		
		# add @games_playing also
		@games_playing = current_user.games_playing
	end
	
	def new
		@game = Game.new
		#need to get current_user from session
	end

	def create
		@game = Game.new(params.require(:game).permit(:name,:game_history,:game_password))
		uploaded_io =  params[:game][:map]
		unless uploaded_io.nil?
			sanitized_filename = sanitize_filename(uploaded_io.original_filename)
		  	sanitized_filename = "#{current_user.user_name}_#{@game.name}_#{sanitized_filename}"
			upload(sanitized_filename,uploaded_io)
			@game.map = sanitized_filename
		end
		@game.dungeon_master = current_user
		
		if @game.save
			flash[:success] =  "Game successfully created!"
			redirect_to game_path(@game)
		else
			render 'new'
		end
	end

	def show
		@game = Game.find(params[:id])	
	end

	def edit
		@game = Game.find(params[:id])
	end


	 def update
  		@game = Game.find(params[:id])
  		game_history = params[:game][:game_history]
  		uploaded_io =  params[:game][:map]
  		game_map = nil
		unless uploaded_io.nil?
			sanitized_filename = sanitize_filename(uploaded_io.original_filename)
		  	sanitized_filename = "#{current_user.user_name}_#{@game.name}_#{sanitized_filename}"
			upload(sanitized_filename,uploaded_io)
			game_map = sanitized_filename
		end
		@game.map = game_map unless game_map.nil?
  		if @game.update(game_history: game_history)
  			redirect_to game_path(@game)
  		else
  			redirect_to games_url
  		end
  	end

  	
	def destroy
		Game.destroy(params[:game_id]);
		redirect_to games_path;
	end
    

   def leaveGame
		@userIDToLeaveGame = params[:user_id];
		@game_to_remove    = Game.find(params[:game_id])
        
        puts @game_to_remove.id
        
        #PlayerCharacter.where("creator_id = ? AND game_id=?", params[:user_id],params[:game_id] ).update(game_id: "nul")
	
        @pc_to_remove      = PlayerCharacter.where("creator_id = ? AND game_id=?", params[:user_id],params[:game_id] )
		
		puts @pc_to_remove
		# @pc_to_remove.update(game_id: '100')
		
		@game_to_remove.player_characters.delete(@pc_to_remove)


		redirect_to games_path(@userIDToLeaveGame);
	end

	private
    # Confirms if the user is dungeon user.
	 def is_dungeon_master_user
	    game = Game.find_by id: params[:id]
	    if game.nil? or !dungeon_master?(game.dungeon_master)
	    	redirect_to(root_url) 
	    end
	 end

	

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.erb
<% provide(:title, "Game-Edit") %>

<h2> Edit Game </h2>

<%= form_for(@game) do |f| %>
 	<table class="table">
 		<tr>
    		<td>Game Name</td><td><%= f.label :name, @game.name%></td>
		</tr>
		<tr>
    		<td>Game Map</td><td><%= f.file_field :map%><% unless @game.map.nil?%><%=  image_tag("/images/uploads/" + @game.map, size: "200x200", alt: "Game Map")%><% end %></td>
		</tr>
		<tr>
    		<td>Game History</td><td><%= f.text_area :game_history , :size=>"50x10"%></td>
		</tr>
		<tr>
    		<td>Game Password</td><td><%= f.label :game_password, @game.game_password%></td>
		</tr>
 	</table>

 	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

 	<p>
   <%= f.submit "Update" %> &nbsp;<%= link_to '<button type="button">Cancel</button>'.html_safe, games_path %>
	</p>

	


<% end %>


app/views/games/index.html.erb
<% provide(:title, 'Games-Index') %>

<div style="margin-top: 10px;">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"> My Active Games </div>

    <!-- Table -->
    <table class="table">
    <tr>
      <th>Game Name</th>
      <th>Dungeon Master</th>
      <th>Player Character</th>
      <th colspan=3 > &nbsp;&nbsp;</th>
    </tr>
    <% @user_owned_games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td>(me)</td>
      <% player_characters = '' 
        game.player_characters.each do |player_character|
          characterInfo = "#{player_character.name}(#{player_character.creator.user_name})"
          if player_characters.length == 0 
            player_characters = characterInfo
          else
            player_characters = "#{player_characters};#{characterInfo}"
          end
        end
          %>
      <td><%= player_characters %></td>
      <td><%= link_to "View", game_path(game),class: 'btn'  %></td>
      <td><%= link_to "Edit", edit_game_path(game),class: 'btn' %></td>
      <td><%= link_to "Delete", games_path(game_id: game.id), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn' %></td>
    </tr>
    <% end %>
    <% @games_playing.each do |game| %>
          <tr>
            <td><%= game.name %></td>
            <td><%= game.dungeon_master.user_name%></td>
            <% player_characters = '' 
                    game.player_characters.each do |player_character|
                          characterInfo = "#{player_character.name}(#{player_character.creator.user_name})"
                          characterInfo =  "<span style='font-weight:bold;'>#{characterInfo}</span>" if current_user == player_character.creator

                          if player_characters.length == 0 
                            player_characters = characterInfo
                          else
                            player_characters = "#{player_characters};#{characterInfo}"
                          end
                    end
                %>
            <td><%= raw player_characters %></td>
            <td><%= link_to "View", game_path(game),class: 'btn'  %></td>
            <td>&nbsp;</td>
            <td><%= link_to "Leave", game_path(:id => game.id, :user_id => current_user, :game_id => game.id), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn' %></td>
          </tr>
    <% end %>
    </table>
  </div>

</div>

<div class="col-sm-12">
	<hr>
	<%= link_to "Go to User Home page",user_path(current_user) %>
</div>

app/views/games/new.html.erb
<% provide(:title, "Game-Add") %>


<% if @game.errors.any? %>
<div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
</div>
<% end %>

<div style="margin-top: 10px;">
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">New Game</div>
	  </div>
	  <div style="margin-top: 10px;" >
	  <!-- Table -->
		<%= form_for(@game) do |f| %>
		<div class='form-group'>
			<div class="col-sm-2">
		    	<%= f.label :name,'Game Name:'%>
			</div>
		    <div class="col-sm-10">
		    	<%= f.text_field :name,  class: 'form-control'%>
			</div>
		</div>

		<div style="margin-top: 10px;" />
		<div class='form-group'>
			<div class="col-sm-2">
		    	<%= f.label :game_password,'Game Password:'%>
			</div>
		    <div class="col-sm-10">
		    	<%= f.password_field :game_password,  class: 'form-control'%>
		    </div>
		</div>
		<div style="margin-top: 10px;" />
		<div class='form-group'>
			<div class="col-sm-2">
		    	<%= f.label :map,'Game Map:'%>
			</div>
		    <div class="col-sm-10">
		    	<%= f.file_field :map,  class: 'form-control'%>
		    </div>
		</div>
		<div style="margin-top: 10px;" />
		<div class='form-group'>
			<div class="col-sm-2">
		    	<%= f.label :game_history,'Game History:'%>
			</div>
		    <div class="col-sm-10">
		    	<%= f.text_area :game_history, :size=>"50x10", class: 'form-control'%>
		    </div>
		</div>
		<div style="margin-top: 10px;" />
		<div class="form-group">
	    	<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit "Create Game" %>&nbsp;<%= button_tag "Reset", type: :reset %>
			</div>

		</div>
		<% end %>
	</div>	
	</div>

<div class="col-sm-11">
	<%= link_to "Go to User Home page",user_path(current_user) %>
</div>

app/views/games/show.html.erb
<% provide(:title, "Game-Show") %>
<% if dungeon_master?(@game.dungeon_master) %>
  <ul>
  	<li style = "list-style:none;"><%= link_to "Edit Game",edit_game_path(@game)%> | <%= link_to "Invite Users",new_game_invitation_path(@game) %>| <%= link_to "Assign Exp Points",experiencepoints_path(@game) %>
      | <%= link_to "Assign Achievements",achievements_path(@game) %></li>
  </ul>
<% end %>
<h2> Game Details: </h2>
<table class = "table">
  <tr>
    <td>Game Name</td><td><%= @game.name%></td>
</tr>
<tr>
    <td>Dungeon Master </td><td><%= (dungeon_master?(@game.dungeon_master)) ? ("(me)") : (@game.dungeon_master.user_name)%></td>
</tr>
<tr>
    <td>Game Map</td><td><% unless @game.map.nil?%><%=  image_tag("/images/uploads/" + @game.map, size: "200x200", alt: "Game Map")%><% end %></td>
</tr>
<tr>
    <td>Game History</td><td><%= @game.game_history%></td>
</tr>
<tr>
    <td>Game Password</td><td><%= @game.game_password%></td>
</tr>
<tr>
    <td>Game Players</td>
    <td><% player_characters = '' 
      @game.player_characters.each do |player_character|

        if player_characters.length == 0 %>
        <%=link_to player_character.name, player_character_path(:id=>player_character.id, :dm_id => @game.dungeon_master.id), method: :get %>
         <!--player_characters = player_character.name -->
        <% else %>
        <!-- player_characters = "#{player_characters};#{player_character.name}"-->
        <%=link_to player_character.name, player_character_path(:id=>player_character.id, :dm_id => @game.dungeon_master.id), method: :getexit %>
        
       <% end 
       end%></td>
 </tr>



</table>


<% if dungeon_master?(@game.dungeon_master) %>
	<h2> Pending Game Invitation </h2>
	<table width="100%">
		<tr><th align='left'>Dungeon Master </th>
			<th align='left'>Invited Users </th>
			<th align='left'> &nbsp;</th>
		</tr>
		<% @game.game_invitations.each do |game_invitation| %>
		<tr>
			<td>(me)</td>
			<td><%= game_invitation.user_player.user_name %></td>
			<td>Cancel</td>
		</tr>
		<% end %>
	</table>
<% end %>



<br>
<br>
<hr>

<%= link_to "Go to User Home page",user_path(current_user) %>